### ISSUE TITLE
Robot is way too wobbly

### ISSUE THREAD

**Issue by threos** [Ozyegin-Planetary-Robotics-Laboratory/ares_arm_simulation#6]
The robot wobbles too much at the beginning of the simulation and whenever joints move. This creates a bigger problem for our control system because that "wobble" motion causes joint and position states to go beyond "goal tolerance" defined by MoveIt, causing the operation to abort and fail.

I think tuning PID or playing with URDF might help @sedenmutaf1. If you want to test different PID values you can use the "ares_arm_moveit" package too. You can find PID values for each joint in config/ros_controllers.yaml. If you have any problems with that package you can let me know too. I'll be writing a document but until then I can help you do the troubleshooting (there are some setup needs to be done for MoveIt).

**Comment by Toprak-Efe** [comment]
Fixed with PID tuning
